name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn
  - streamlit
  - shap
  - pandas
  - numpy
  - matplotlib
  - joblib
  - ipython
  - pip
  - pip:
     

