name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn>=1.5.1
  - streamlit
  - shap
  - pandas
  - numpy
  - matplotlib
  - joblib
  - ipython
  - wheel
  - setuptools
  - menuinst
  - pip